In [1]:
import pandas as pd
import numpy as np
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import matthews_corrcoef
from scipy import stats
import scipy

In [2]:
df = pd.read_csv('illiteracy.txt', sep='\t')

In [3]:
df.head()

Country  Illit  Births
0  Albania   20.5    1.78
1  Algeria   39.1    2.44
2  Bahrain   15.0    2.34
3   Belize    5.9    2.97
4    Benin   73.5    5.60

In [4]:
pearsonr(df.Illit, df.Births)

(0.7686630271151789, 1.5029095259924921e-19)

In [5]:
spearmanr(df.Illit, df.Births)

SpearmanrResult(correlation=0.752962213732534, pvalue=2.0858571221460674e-18)

In [6]:
df = pd.read_csv('water.txt', sep='\t')

In [8]:
df.corr()

mortality  hardness
mortality   1.000000 -0.654849
hardness   -0.654849  1.000000

In [9]:
spearmanr(df.mortality, df.hardness)

SpearmanrResult(correlation=-0.6316646189166502, pvalue=4.79546153722838e-08)

In [11]:
south = df[df.location == 'South']
north = df[df.location == 'North']

In [12]:
south.corr()

mortality  hardness
mortality   1.000000 -0.602153
hardness   -0.602153  1.000000

In [13]:
north.corr()

mortality  hardness
mortality   1.000000 -0.368598
hardness   -0.368598  1.000000

In [15]:
matthews_corrcoef()

203 239
718 515



SyntaxError: invalid syntax (<ipython-input-15-a2f19bc08c8e>, line 3)

In [16]:
obs = np.array([[203, 239], [718, 515]])

In [18]:
stats.chi2_contingency(obs)[0]/()

(19.40753078854304,
 1.0558987006638725e-05,
 1,
 array([[243.03402985, 198.96597015],
        [677.96597015, 555.03402985]]))

In [21]:
[203, 239], 
[718, 515]

[718, 515]

In [22]:
(203*515 - 239*718)/(np.sqrt((203+239)*(203+718)*(239+515)*(718+515)))

-0.10900237458678963

In [23]:
def proportions_confint_diff_ind(sample1, sample2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)   
    p1 = float(sum(sample1)) / len(sample1)
    p2 = float(sum(sample2)) / len(sample2)
    
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    
    return (left_boundary, right_boundary)

In [39]:
alpha = 0.05
p2 = 203/(203+718)
p1 = 239 /(239+515)
n2 = (203+718)
n1 = (239+515)
z = scipy.stats.norm.ppf(1 - alpha / 2.)  
left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ n1 + p2 * (1 - p2)/n2)
right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ n1 + p2 * (1 - p2)/n2)

In [40]:
left_boundary, right_boundary

(0.053905233215813156, 0.13922183141523897)

In [32]:
P = float(p1*n1 + p2*n2) / (n1 + n2)    
z_stat = (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))

In [33]:
2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))

8.153453089576601e-06

In [37]:
observ = np.array([[197,111,33],[382,685,331],[110, 342, 333]])
chi2 = stats.chi2_contingency(observ)[0]

In [38]:
n = observ.sum()
chi2/n

0.11635622440447602

In [1]:
from statsmodels.sandbox.stats.multicomp import multipletests 

In [4]:
dff = pd.read_csv('AUCs.txt', sep='\t')

In [6]:
dff

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0            adult (sample)  0.763   0.768    0.771      0.798
1             breast cancer  0.599   0.591    0.590      0.569
2   breast cancer wisconsin  0.954   0.971    0.968      0.967
3                       cmc  0.628   0.661    0.654      0.657
4                ionosphere  0.882   0.888    0.886      0.898
5                      iris  0.936   0.931    0.916      0.931
6           liver disorders  0.661   0.668    0.609      0.685
7               lung cancer  0.583   0.583    0.563      0.625
8              lymphography  0.775   0.838    0.866      0.875
9                  mushroom  1.000   1.000    1.000      1.000
10            primary tumor  0.940   0.962    0.965      0.962
11                    rheum  0.619   0.666    0.614      0.669
12                   voting  0.972   0.981    0.975      0.975
13                     wine  0.957   0.978    0.946      0.970

In [7]:
def mann(sample1, sample2):
    return stats.mannwhitneyu(sample1, sample2)[1]

In [9]:
dff.corr(method=mann)

C4.5    C4.5+m   C4.5+cf  C4.5+m+cf
C4.5       1.000000  0.322878  0.500000   0.306606
C4.5+m     0.322878  1.000000  0.339589   0.500000
C4.5+cf    0.500000  0.339589  1.000000   0.314696
C4.5+m+cf  0.306606  0.500000  0.314696   1.000000

In [11]:
dff.columns

Index(['Unnamed: 0', 'C4.5', 'C4.5+m', 'C4.5+cf', 'C4.5+m+cf'], dtype='object')

In [12]:
cols = ['C4.5', 'C4.5+m', 'C4.5+cf', 'C4.5+m+cf']

In [28]:
pcor = []
for i in range(len(cols)-1):
    for j in range(i+1, len(cols)):
        print(stats.wilcoxon(dff[cols[i]], dff[cols[j]]), cols[i], cols[j])
        pcor.append(stats.wilcoxon(dff[cols[i]], dff[cols[j]])[1])

WilcoxonResult(statistic=6.5, pvalue=0.01075713311978963) C4.5 C4.5+m
WilcoxonResult(statistic=43.0, pvalue=0.861262330095348) C4.5 C4.5+cf
WilcoxonResult(statistic=11.0, pvalue=0.015906444101703374) C4.5 C4.5+m+cf
WilcoxonResult(statistic=17.0, pvalue=0.046332729793395394) C4.5+m C4.5+cf
WilcoxonResult(statistic=22.0, pvalue=0.3278256758446406) C4.5+m C4.5+m+cf
WilcoxonResult(statistic=10.0, pvalue=0.022909099354356588) C4.5+cf C4.5+m+cf


In [29]:
from statsmodels.sandbox.stats.multicomp import multipletests 

In [30]:
multipletests(pcor, method='holm', alpha=0.05)

(array([False, False, False, False, False, False]),
 array([0.0645428 , 0.86126233, 0.07953222, 0.13899819, 0.65565135,
        0.0916364 ]),
 0.008512444610847103,
 0.008333333333333333)

In [31]:
multipletests(pcor, method='fdr_bh', alpha=0.05)

(array([ True, False,  True, False, False,  True]),
 array([0.0458182 , 0.86126233, 0.0458182 , 0.06949909, 0.39339081,
        0.0458182 ]),
 0.008512444610847103,
 0.008333333333333333)

In [32]:
from sklearn.metrics import roc_auc_score

In [33]:
roc_auc_score([0,1,0,0,1,0], [0.0,0.1,0.1,0.33,0.9,0.9])

0.625

In [34]:
from sklearn. import log_loss

In [35]:
log_loss([0, 1, 0, 0, 1],[0.2, 0.534, 0, 1, 0.99])

7.080025863906106

In [2]:
df = pd.read_csv('botswana.tsv', sep='\t')

In [3]:
df.head()

ceb  age  educ    religion  idlnchld  knowmeth  usemeth  evermarr  agefm  \
0    0   18    10    catholic       4.0       1.0      1.0         0    NaN   
1    2   43    11  protestant       2.0       1.0      1.0         1   20.0   
2    0   49     4      spirit       4.0       1.0      0.0         1   22.0   
3    0   24    12       other       2.0       1.0      0.0         0    NaN   
4    3   32    13       other       3.0       1.0      1.0         1   24.0   

   heduc  urban  electric  radio   tv  bicycle  
0    NaN      1       1.0    1.0  1.0      1.0  
1   14.0      1       1.0    1.0  1.0      1.0  
2    1.0      1       1.0    1.0  0.0      0.0  
3    NaN      1       1.0    1.0  1.0      1.0  
4   12.0      1       1.0    1.0  1.0      1.0

In [4]:
df.religion.value_counts()

spirit        1841
other         1080
protestant     993
catholic       447
Name: religion, dtype: int64

In [5]:
df1 = df.dropna()

In [6]:
df1.shape

(1834, 15)

In [18]:
df['nevermarr'] = np.where(df.agefm.isnull(),1,0)

In [20]:
df2 = df.drop(columns='evermarr')

In [21]:
df2.agefm.fillna(0, inplace=True)

In [24]:
df2['heduc'] = np.where(df2.nevermarr == 1, -1, df2.heduc)

In [28]:
df2.heduc.count()

4238

In [27]:
df.heduc.count()

1956

In [30]:
df.shape[0]-df2.heduc.count()

123

In [31]:
df2['idlnchld_noans'] = np.where(df2.idlnchld.isnull(), 1, 0)
df2.idlnchld.fillna(-1, inplace=True)
df2['heduc_noans'] = np.where(df2.heduc.isnull(), 1, 0)
df2.heduc.fillna(-2, inplace=True)
df2['usemeth_noans'] = np.where(df2.usemeth.isnull(), 1, 0)
df2.usemeth.fillna(-1, inplace=True)


In [32]:
df3 = df2.dropna()

In [36]:
df3.columns

Index(['ceb', 'age', 'educ', 'religion', 'idlnchld', 'knowmeth', 'usemeth',
       'agefm', 'heduc', 'urban', 'electric', 'radio', 'tv', 'bicycle',
       'nevermarr', 'idlnchld_noans', 'heduc_noans', 'usemeth_noans'],
      dtype='object')

In [34]:
df3.shape[0]*df3.shape[1]

78264

In [40]:
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms

In [37]:
m1 = smf.ols('ceb ~ age + educ + religion + idlnchld + knowmeth + usemeth + agefm + heduc + urban + electric + radio + tv + bicycle + nevermarr + idlnchld_noans + heduc_noans + usemeth_noans',
             data=df3)
fitted = m1.fit()
print(fitted.summary())

                            OLS Regression Results                            
Dep. Variable:                    ceb   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     412.5
Date:                Mon, 23 Mar 2020   Prob (F-statistic):               0.00
Time:                        10:00:24   Log-Likelihood:                -7732.1
No. Observations:                4348   AIC:                         1.550e+04
Df Residuals:                    4328   BIC:                         1.563e+04
Df Model:                          19                                         
Covariance Type:            nonrobust                                         
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -1

In [41]:
sms.het_breuschpagan(fitted.resid, fitted.model.exog)[1]

1.1452927633437192e-225

In [42]:
df4 = df3.drop(columns=['radio', 'tv', 'religion'])

In [43]:
m2 = smf.ols('ceb ~ age + educ + idlnchld + knowmeth + usemeth + agefm + heduc + urban + electric + bicycle + nevermarr + idlnchld_noans + heduc_noans + usemeth_noans',
             data=df4)
fitted = m2.fit(cov_type='HC1')
print(fitted.summary())

                            OLS Regression Results                            
Dep. Variable:                    ceb   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     463.4
Date:                Mon, 23 Mar 2020   Prob (F-statistic):               0.00
Time:                        10:04:58   Log-Likelihood:                -7734.5
No. Observations:                4348   AIC:                         1.550e+04
Df Residuals:                    4333   BIC:                         1.559e+04
Df Model:                          14                                         
Covariance Type:                  HC1                                         
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -1.0698      0.258     -4.

In [45]:
m1.fit().compare_f_test(m2.fit())

(0.919235778463167, 0.467230554727435, 5.0)

In [46]:
df5 = df4.drop(columns=['usemeth_noans', 'usemeth'])

In [48]:
m3 = smf.ols('ceb ~ age + educ + idlnchld + knowmeth  + agefm + heduc + urban + electric + bicycle + nevermarr + idlnchld_noans + heduc_noans ',
             data=df5)
fitted = m3.fit(cov_type='HC1')
print(fitted.summary())

                            OLS Regression Results                            
Dep. Variable:                    ceb   R-squared:                       0.629
Model:                            OLS   Adj. R-squared:                  0.628
Method:                 Least Squares   F-statistic:                     396.4
Date:                Mon, 23 Mar 2020   Prob (F-statistic):               0.00
Time:                        10:08:41   Log-Likelihood:                -7825.7
No. Observations:                4348   AIC:                         1.568e+04
Df Residuals:                    4335   BIC:                         1.576e+04
Df Model:                          12                                         
Covariance Type:                  HC1                                         
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -1.1931      0.262     -4.

In [49]:
m2.fit().compare_f_test(m3.fit())

(92.89058230109713, 3.155200948040263e-40, 2.0)